---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "iris.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "iris.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - services
      - namespaces
      - endpoints
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding
metadata:
  name: {{ template "iris.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "iris.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "iris.fullname" . }}
    namespace: {{ .Release.Namespace }}
