{{- if .Values.iris.tlsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "iris.fullname" . }}
  labels:
    app: {{ template "iris.name" . }}
    chart: {{ template "iris.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ ((print .Values.iris.localSecretsPath "/*") | .Files.Glob).AsSecrets | indent 2 }}
{{- end }}
