apiVersion: v1
kind: Service
metadata:
  name: {{ template "iris.fullname" . }}
  labels:
    app: {{ template "iris.name" . }}
    chart: {{ template "iris.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: iris
      protocol: TCP
      name: iris
  selector:
    app: {{ template "iris.name" . }}
    release: {{ .Release.Name }}
